FROM centos:centos6
MAINTAINER Leo Laksmana <beol@laksmana.com>

RUN curl -sS --cookie 'oraclelicense=accept-securebackup-cookie' -L \
         -o /tmp/jdk-8u121-linux-x64.rpm \
         http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm \
         && \
         yum localinstall -y /tmp/jdk-8u121-linux-x64.rpm . \
         && \
         rm -f /tmp/jdk-8u121-linux-x64.rpm

ENV JAVA_HOME /usr/java/default

